apiVersion: apps/v1
kind: Deployment
metadata:
  name: apik8s-deployment
  labels:
    app: apik8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apik8s
  template:
    metadata:
      labels:
        app: apik8s
    spec:
      containers:
      - name: apik8s
        image: tekigai/kubernetes_part3:dev
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name : apik8s-config
              key: apik8s-env
        - name: ApplicationOptions__Title
          valueFrom:
            configMapKeyRef:
              name : apik8s-config
              key: title
        - name: QuoteStoreDatabase__DbUrl
          valueFrom:
            configMapKeyRef:
              name : apik8s-config
              key: dburl
        - name: QuoteStoreDatabase__User
          valueFrom:
            secretKeyRef:
              name : mongo-secret
              key: user
        - name: QuoteStoreDatabase__Pwd
          valueFrom:
            secretKeyRef:
              name : mongo-secret
              key: password


---
apiVersion: v1
kind: Service
metadata:
  name: apik8s-service
spec:
  type: NodePort
  selector:
    app: apik8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
